# Generated by Django 2.0.3 on 2018-03-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmonitor',
            name='currency_name',
            field=models.CharField(default='Bitcoin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinmonitor',
            name='icon_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
