# Generated by Django 2.0.3 on 2018-03-24 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coins_monitor', '0003_buyoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyoperation',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
