# Generated by Django 2.0.3 on 2018-03-24 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coins_monitor', '0004_buyoperation_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyoperation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
