# Generated by Django 2.0.3 on 2018-03-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins_monitor', '0005_auto_20180324_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyoperation',
            options={'ordering': ['-timestamp']},
        ),
    ]
